Search.appendIndex(
    [
                {
            "fqsen": "\\App\\Http\\Controllers\\AnswerContoller",
            "name": "AnswerContoller",
            "summary": "",
            "url": "classes/App-Http-Controllers-AnswerContoller.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AnswerContoller\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Display\u0020a\u0020listing\u0020of\u0020surveys.",
            "url": "classes/App-Http-Controllers-AnswerContoller.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AnswerContoller\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "Store\u0020a\u0020newly\u0020created\u0020resource\u0020in\u0020storage.",
            "url": "classes/App-Http-Controllers-AnswerContoller.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AnswerContoller\u003A\u003AstoreForParticipant\u0028\u0029",
            "name": "storeForParticipant",
            "summary": "Enregistrements\u0020des\u0020r\u00E9ponses\u0020envoy\u00E9\u0020par\u0020l\u0027utilisateur",
            "url": "classes/App-Http-Controllers-AnswerContoller.html#method_storeForParticipant"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AnswerContoller\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Update\u0020the\u0020specified\u0020resource\u0020in\u0020storage.",
            "url": "classes/App-Http-Controllers-AnswerContoller.html#method_update"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AnswerContoller\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "Remove\u0020the\u0020specified\u0020resource\u0020from\u0020storage.",
            "url": "classes/App-Http-Controllers-AnswerContoller.html#method_destroy"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AnswerContoller\u003A\u003AgetCountValue\u0028\u0029",
            "name": "getCountValue",
            "summary": "Obtenir\u0020le\u0020nombres\u0020de\u0020repetion\u0020de\u0020la\u0020reponse",
            "url": "classes/App-Http-Controllers-AnswerContoller.html#method_getCountValue"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AnswerContoller\u003A\u003AgetParticipantAnswersClient\u0028\u0029",
            "name": "getParticipantAnswersClient",
            "summary": "",
            "url": "classes/App-Http-Controllers-AnswerContoller.html#method_getParticipantAnswersClient"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AnswerContoller\u003A\u003AgetParticipantAnswersAdmin\u0028\u0029",
            "name": "getParticipantAnswersAdmin",
            "summary": "",
            "url": "classes/App-Http-Controllers-AnswerContoller.html#method_getParticipantAnswersAdmin"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AuthController",
            "name": "AuthController",
            "summary": "",
            "url": "classes/App-Http-Controllers-AuthController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AuthController\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "Inscription\u0020de\u0020l\u0027utilisateur\u0020et\u0020rtourne\u0020son\u0020token\u0020de\u0020connexion",
            "url": "classes/App-Http-Controllers-AuthController.html#method_register"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AuthController\u003A\u003Alogin\u0028\u0029",
            "name": "login",
            "summary": "Authentification\u0020de\u0020l\u0027utilisateur",
            "url": "classes/App-Http-Controllers-AuthController.html#method_login"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AuthController\u003A\u003Ame\u0028\u0029",
            "name": "me",
            "summary": "Recuperation\u0020de\u0020donn\u00E9es\u0020de\u0020l\u0027utilisateur\u0020connect\u00E9",
            "url": "classes/App-Http-Controllers-AuthController.html#method_me"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AuthController\u003A\u003ArevokeToken\u0028\u0029",
            "name": "revokeToken",
            "summary": "Suppression\u0020du\u0020token\u0020de\u0020l\u0027utilisateur",
            "url": "classes/App-Http-Controllers-AuthController.html#method_revokeToken"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Controller",
            "name": "Controller",
            "summary": "",
            "url": "classes/App-Http-Controllers-Controller.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ParticipantController",
            "name": "ParticipantController",
            "summary": "",
            "url": "classes/App-Http-Controllers-ParticipantController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ParticipantController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Display\u0020a\u0020listing\u0020of\u0020the\u0020resource.",
            "url": "classes/App-Http-Controllers-ParticipantController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ParticipantController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "Store\u0020a\u0020newly\u0020created\u0020resource\u0020in\u0020storage.",
            "url": "classes/App-Http-Controllers-ParticipantController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ParticipantController\u003A\u003Ashow\u0028\u0029",
            "name": "show",
            "summary": "Display\u0020the\u0020specified\u0020resource.",
            "url": "classes/App-Http-Controllers-ParticipantController.html#method_show"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ParticipantController\u003A\u003Aedit\u0028\u0029",
            "name": "edit",
            "summary": "Show\u0020the\u0020form\u0020for\u0020editing\u0020the\u0020specified\u0020resource.",
            "url": "classes/App-Http-Controllers-ParticipantController.html#method_edit"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ParticipantController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Update\u0020the\u0020specified\u0020resource\u0020in\u0020storage.",
            "url": "classes/App-Http-Controllers-ParticipantController.html#method_update"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ParticipantController\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "Remove\u0020the\u0020specified\u0020resource\u0020from\u0020storage.",
            "url": "classes/App-Http-Controllers-ParticipantController.html#method_destroy"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ParticipantController\u003A\u003AgetAdminParticipant\u0028\u0029",
            "name": "getAdminParticipant",
            "summary": "",
            "url": "classes/App-Http-Controllers-ParticipantController.html#method_getAdminParticipant"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\QuestionController",
            "name": "QuestionController",
            "summary": "",
            "url": "classes/App-Http-Controllers-QuestionController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\QuestionController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Display\u0020a\u0020listing\u0020of\u0020the\u0020resource.",
            "url": "classes/App-Http-Controllers-QuestionController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\QuestionController\u003A\u003AfindByTokenSurvey\u0028\u0029",
            "name": "findByTokenSurvey",
            "summary": "",
            "url": "classes/App-Http-Controllers-QuestionController.html#method_findByTokenSurvey"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\QuestionController\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Show\u0020the\u0020form\u0020for\u0020creating\u0020a\u0020new\u0020resource.",
            "url": "classes/App-Http-Controllers-QuestionController.html#method_create"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\QuestionController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "Store\u0020a\u0020newly\u0020created\u0020resource\u0020in\u0020storage.",
            "url": "classes/App-Http-Controllers-QuestionController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\QuestionController\u003A\u003Ashow\u0028\u0029",
            "name": "show",
            "summary": "Display\u0020the\u0020specified\u0020resource.",
            "url": "classes/App-Http-Controllers-QuestionController.html#method_show"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\QuestionController\u003A\u003Aedit\u0028\u0029",
            "name": "edit",
            "summary": "Show\u0020the\u0020form\u0020for\u0020editing\u0020the\u0020specified\u0020resource.",
            "url": "classes/App-Http-Controllers-QuestionController.html#method_edit"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\QuestionController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Update\u0020the\u0020specified\u0020resource\u0020in\u0020storage.",
            "url": "classes/App-Http-Controllers-QuestionController.html#method_update"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\QuestionController\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "Remove\u0020the\u0020specified\u0020resource\u0020from\u0020storage.",
            "url": "classes/App-Http-Controllers-QuestionController.html#method_destroy"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\SurveyController",
            "name": "SurveyController",
            "summary": "",
            "url": "classes/App-Http-Controllers-SurveyController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\SurveyController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Display\u0020a\u0020listing\u0020of\u0020surveys.",
            "url": "classes/App-Http-Controllers-SurveyController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\SurveyController\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Show\u0020the\u0020form\u0020for\u0020creating\u0020a\u0020new\u0020resource.",
            "url": "classes/App-Http-Controllers-SurveyController.html#method_create"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\SurveyController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "Store\u0020a\u0020newly\u0020created\u0020resource\u0020in\u0020storage.",
            "url": "classes/App-Http-Controllers-SurveyController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\SurveyController\u003A\u003Ashow\u0028\u0029",
            "name": "show",
            "summary": "Display\u0020the\u0020specified\u0020resource.",
            "url": "classes/App-Http-Controllers-SurveyController.html#method_show"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\SurveyController\u003A\u003Aedit\u0028\u0029",
            "name": "edit",
            "summary": "Show\u0020the\u0020form\u0020for\u0020editing\u0020the\u0020specified\u0020resource.",
            "url": "classes/App-Http-Controllers-SurveyController.html#method_edit"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\SurveyController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Update\u0020the\u0020specified\u0020resource\u0020in\u0020storage.",
            "url": "classes/App-Http-Controllers-SurveyController.html#method_update"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\SurveyController\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "Remove\u0020the\u0020specified\u0020resource\u0020from\u0020storage.",
            "url": "classes/App-Http-Controllers-SurveyController.html#method_destroy"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\SurveyController\u003A\u003AfindByTokenParticipant\u0028\u0029",
            "name": "findByTokenParticipant",
            "summary": "",
            "url": "classes/App-Http-Controllers-SurveyController.html#method_findByTokenParticipant"
        },                {
            "fqsen": "\\App\\Http\\Requests\\AnswerRequest",
            "name": "AnswerRequest",
            "summary": "",
            "url": "classes/App-Http-Requests-AnswerRequest.html"
        },                {
            "fqsen": "\\App\\Http\\Requests\\AnswerRequest\u003A\u003Aauthorize\u0028\u0029",
            "name": "authorize",
            "summary": "Determine\u0020if\u0020the\u0020user\u0020is\u0020authorized\u0020to\u0020make\u0020this\u0020request.",
            "url": "classes/App-Http-Requests-AnswerRequest.html#method_authorize"
        },                {
            "fqsen": "\\App\\Http\\Requests\\AnswerRequest\u003A\u003Arules\u0028\u0029",
            "name": "rules",
            "summary": "Get\u0020the\u0020validation\u0020rules\u0020that\u0020apply\u0020to\u0020the\u0020request.",
            "url": "classes/App-Http-Requests-AnswerRequest.html#method_rules"
        },                {
            "fqsen": "\\App\\Http\\Requests\\AnswerRequest\u003A\u003Amessages\u0028\u0029",
            "name": "messages",
            "summary": "Get\u0020the\u0020error\u0020messages\u0020for\u0020the\u0020defined\u0020validation\u0020rules.",
            "url": "classes/App-Http-Requests-AnswerRequest.html#method_messages"
        },                {
            "fqsen": "\\App\\Http\\Requests\\AnswerRequest\u003A\u003AfailedValidation\u0028\u0029",
            "name": "failedValidation",
            "summary": "",
            "url": "classes/App-Http-Requests-AnswerRequest.html#method_failedValidation"
        },                {
            "fqsen": "\\App\\Http\\Requests\\LoginRequest",
            "name": "LoginRequest",
            "summary": "",
            "url": "classes/App-Http-Requests-LoginRequest.html"
        },                {
            "fqsen": "\\App\\Http\\Requests\\LoginRequest\u003A\u003Aauthorize\u0028\u0029",
            "name": "authorize",
            "summary": "Determine\u0020if\u0020the\u0020user\u0020is\u0020authorized\u0020to\u0020make\u0020this\u0020request.",
            "url": "classes/App-Http-Requests-LoginRequest.html#method_authorize"
        },                {
            "fqsen": "\\App\\Http\\Requests\\LoginRequest\u003A\u003Arules\u0028\u0029",
            "name": "rules",
            "summary": "Get\u0020the\u0020validation\u0020rules\u0020that\u0020apply\u0020to\u0020the\u0020request.",
            "url": "classes/App-Http-Requests-LoginRequest.html#method_rules"
        },                {
            "fqsen": "\\App\\Http\\Requests\\LoginRequest\u003A\u003AfailedValidation\u0028\u0029",
            "name": "failedValidation",
            "summary": "",
            "url": "classes/App-Http-Requests-LoginRequest.html#method_failedValidation"
        },                {
            "fqsen": "\\App\\Http\\Requests\\ParticipantRequest",
            "name": "ParticipantRequest",
            "summary": "",
            "url": "classes/App-Http-Requests-ParticipantRequest.html"
        },                {
            "fqsen": "\\App\\Http\\Requests\\ParticipantRequest\u003A\u003Aauthorize\u0028\u0029",
            "name": "authorize",
            "summary": "Determine\u0020if\u0020the\u0020user\u0020is\u0020authorized\u0020to\u0020make\u0020this\u0020request.",
            "url": "classes/App-Http-Requests-ParticipantRequest.html#method_authorize"
        },                {
            "fqsen": "\\App\\Http\\Requests\\ParticipantRequest\u003A\u003Arules\u0028\u0029",
            "name": "rules",
            "summary": "Get\u0020the\u0020validation\u0020rules\u0020that\u0020apply\u0020to\u0020the\u0020request.",
            "url": "classes/App-Http-Requests-ParticipantRequest.html#method_rules"
        },                {
            "fqsen": "\\App\\Http\\Requests\\ParticipantRequest\u003A\u003AfailedValidation\u0028\u0029",
            "name": "failedValidation",
            "summary": "",
            "url": "classes/App-Http-Requests-ParticipantRequest.html#method_failedValidation"
        },                {
            "fqsen": "\\App\\Http\\Requests\\RegisterRequest",
            "name": "RegisterRequest",
            "summary": "",
            "url": "classes/App-Http-Requests-RegisterRequest.html"
        },                {
            "fqsen": "\\App\\Http\\Requests\\RegisterRequest\u003A\u003Aauthorize\u0028\u0029",
            "name": "authorize",
            "summary": "Determine\u0020if\u0020the\u0020user\u0020is\u0020authorized\u0020to\u0020make\u0020this\u0020request.",
            "url": "classes/App-Http-Requests-RegisterRequest.html#method_authorize"
        },                {
            "fqsen": "\\App\\Http\\Requests\\RegisterRequest\u003A\u003Arules\u0028\u0029",
            "name": "rules",
            "summary": "Get\u0020the\u0020validation\u0020rules\u0020that\u0020apply\u0020to\u0020the\u0020request.",
            "url": "classes/App-Http-Requests-RegisterRequest.html#method_rules"
        },                {
            "fqsen": "\\App\\Http\\Requests\\RegisterRequest\u003A\u003AfailedValidation\u0028\u0029",
            "name": "failedValidation",
            "summary": "",
            "url": "classes/App-Http-Requests-RegisterRequest.html#method_failedValidation"
        },                {
            "fqsen": "\\App\\Http\\Requests\\StoreAnswerForParticipantRequest",
            "name": "StoreAnswerForParticipantRequest",
            "summary": "",
            "url": "classes/App-Http-Requests-StoreAnswerForParticipantRequest.html"
        },                {
            "fqsen": "\\App\\Http\\Requests\\StoreAnswerForParticipantRequest\u003A\u003Aauthorize\u0028\u0029",
            "name": "authorize",
            "summary": "Determine\u0020if\u0020the\u0020user\u0020is\u0020authorized\u0020to\u0020make\u0020this\u0020request.",
            "url": "classes/App-Http-Requests-StoreAnswerForParticipantRequest.html#method_authorize"
        },                {
            "fqsen": "\\App\\Http\\Requests\\StoreAnswerForParticipantRequest\u003A\u003Arules\u0028\u0029",
            "name": "rules",
            "summary": "Get\u0020the\u0020validation\u0020rules\u0020that\u0020apply\u0020to\u0020the\u0020request.",
            "url": "classes/App-Http-Requests-StoreAnswerForParticipantRequest.html#method_rules"
        },                {
            "fqsen": "\\App\\Http\\Requests\\StoreAnswerForParticipantRequest\u003A\u003AfailedValidation\u0028\u0029",
            "name": "failedValidation",
            "summary": "",
            "url": "classes/App-Http-Requests-StoreAnswerForParticipantRequest.html#method_failedValidation"
        },                {
            "fqsen": "\\App\\Http\\Resources\\AnswerFullResource",
            "name": "AnswerFullResource",
            "summary": "",
            "url": "classes/App-Http-Resources-AnswerFullResource.html"
        },                {
            "fqsen": "\\App\\Http\\Resources\\AnswerFullResource\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Transform\u0020the\u0020resource\u0020into\u0020an\u0020array.",
            "url": "classes/App-Http-Resources-AnswerFullResource.html#method_toArray"
        },                {
            "fqsen": "\\App\\Http\\Resources\\AnswerRessource",
            "name": "AnswerRessource",
            "summary": "",
            "url": "classes/App-Http-Resources-AnswerRessource.html"
        },                {
            "fqsen": "\\App\\Http\\Resources\\AnswerRessource\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Transform\u0020the\u0020resource\u0020into\u0020an\u0020array.",
            "url": "classes/App-Http-Resources-AnswerRessource.html#method_toArray"
        },                {
            "fqsen": "\\App\\Http\\Resources\\ParticipantFullResource",
            "name": "ParticipantFullResource",
            "summary": "",
            "url": "classes/App-Http-Resources-ParticipantFullResource.html"
        },                {
            "fqsen": "\\App\\Http\\Resources\\ParticipantFullResource\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Transform\u0020the\u0020resource\u0020into\u0020an\u0020array.",
            "url": "classes/App-Http-Resources-ParticipantFullResource.html#method_toArray"
        },                {
            "fqsen": "\\App\\Http\\Resources\\ParticipantRessource",
            "name": "ParticipantRessource",
            "summary": "",
            "url": "classes/App-Http-Resources-ParticipantRessource.html"
        },                {
            "fqsen": "\\App\\Http\\Resources\\ParticipantRessource\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Transform\u0020the\u0020resource\u0020into\u0020an\u0020array.",
            "url": "classes/App-Http-Resources-ParticipantRessource.html#method_toArray"
        },                {
            "fqsen": "\\App\\Http\\Resources\\PropositionResource",
            "name": "PropositionResource",
            "summary": "",
            "url": "classes/App-Http-Resources-PropositionResource.html"
        },                {
            "fqsen": "\\App\\Http\\Resources\\PropositionResource\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Transform\u0020the\u0020resource\u0020into\u0020an\u0020array.",
            "url": "classes/App-Http-Resources-PropositionResource.html#method_toArray"
        },                {
            "fqsen": "\\App\\Http\\Resources\\QuestionLightResource",
            "name": "QuestionLightResource",
            "summary": "",
            "url": "classes/App-Http-Resources-QuestionLightResource.html"
        },                {
            "fqsen": "\\App\\Http\\Resources\\QuestionLightResource\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Transform\u0020the\u0020resource\u0020into\u0020an\u0020array.",
            "url": "classes/App-Http-Resources-QuestionLightResource.html#method_toArray"
        },                {
            "fqsen": "\\App\\Http\\Resources\\QuestionResource",
            "name": "QuestionResource",
            "summary": "",
            "url": "classes/App-Http-Resources-QuestionResource.html"
        },                {
            "fqsen": "\\App\\Http\\Resources\\QuestionResource\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Transform\u0020the\u0020resource\u0020into\u0020an\u0020array.",
            "url": "classes/App-Http-Resources-QuestionResource.html#method_toArray"
        },                {
            "fqsen": "\\App\\Http\\Resources\\SurveyResource",
            "name": "SurveyResource",
            "summary": "",
            "url": "classes/App-Http-Resources-SurveyResource.html"
        },                {
            "fqsen": "\\App\\Http\\Resources\\SurveyResource\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Transform\u0020the\u0020resource\u0020into\u0020an\u0020array.",
            "url": "classes/App-Http-Resources-SurveyResource.html#method_toArray"
        },                {
            "fqsen": "\\App\\Models\\Answer",
            "name": "Answer",
            "summary": "",
            "url": "classes/App-Models-Answer.html"
        },                {
            "fqsen": "\\App\\Models\\Answer\u003A\u003Aquestion\u0028\u0029",
            "name": "question",
            "summary": "question\nretourne\u0020la\u0020question\u0020li\u00E9e\u0020\u00E0\u0020cette\u0020r\u00E9ponse",
            "url": "classes/App-Models-Answer.html#method_question"
        },                {
            "fqsen": "\\App\\Models\\Answer\u003A\u003Aparticipant\u0028\u0029",
            "name": "participant",
            "summary": "participant\nretourne\u0020le\u0020participant\u0020qui\u0020a\u0020donn\u00E9\u0020cette\u0020r\u00E9ponse",
            "url": "classes/App-Models-Answer.html#method_participant"
        },                {
            "fqsen": "\\App\\Models\\Answer\u003A\u003AgetCountOfValue\u0028\u0029",
            "name": "getCountOfValue",
            "summary": "Retourne\u0020le\u0020nombre\u0020de\u0020repetions\u0020des\u0020reponse\u0020a\u0020partir\u0020des\u0020numero\u0020de\u0020questions",
            "url": "classes/App-Models-Answer.html#method_getCountOfValue"
        },                {
            "fqsen": "\\App\\Models\\Answer\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "fillable\nLes\u0020attributs\u0020de\u0020Answer\u0020renseignables",
            "url": "classes/App-Models-Answer.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\Participant",
            "name": "Participant",
            "summary": "",
            "url": "classes/App-Models-Participant.html"
        },                {
            "fqsen": "\\App\\Models\\Participant\u003A\u003Asurvey\u0028\u0029",
            "name": "survey",
            "summary": "survey\nr\u00E9cup\u00E8re\u0020le\u0020sondage\u0020de\u0020ce\u0020participant",
            "url": "classes/App-Models-Participant.html#method_survey"
        },                {
            "fqsen": "\\App\\Models\\Participant\u003A\u003Aanswers\u0028\u0029",
            "name": "answers",
            "summary": "",
            "url": "classes/App-Models-Participant.html#method_answers"
        },                {
            "fqsen": "\\App\\Models\\Participant\u003A\u003Asave_answers\u0028\u0029",
            "name": "save_answers",
            "summary": "Creation\u0020du\u0020participant\u0020\u002B\u0020enregistrement\u0020de\u0020ses\u0020reponses",
            "url": "classes/App-Models-Participant.html#method_save_answers"
        },                {
            "fqsen": "\\App\\Models\\Participant\u003A\u003Aclean_answers_object\u0028\u0029",
            "name": "clean_answers_object",
            "summary": "",
            "url": "classes/App-Models-Participant.html#method_clean_answers_object"
        },                {
            "fqsen": "\\App\\Models\\Participant\u003A\u003AfindByToken\u0028\u0029",
            "name": "findByToken",
            "summary": "",
            "url": "classes/App-Models-Participant.html#method_findByToken"
        },                {
            "fqsen": "\\App\\Models\\Participant\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "fillable\nLes\u0020attributs\u0020de\u0020Participant\u0020renseignables",
            "url": "classes/App-Models-Participant.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\Proposition",
            "name": "Proposition",
            "summary": "",
            "url": "classes/App-Models-Proposition.html"
        },                {
            "fqsen": "\\App\\Models\\Proposition\u003A\u003Aquestion\u0028\u0029",
            "name": "question",
            "summary": "question\nr\u00E9cup\u00E8re\u0020la\u0020question\u0020li\u00E9e\u0020\u00E0\u0020cette\u0020proposition",
            "url": "classes/App-Models-Proposition.html#method_question"
        },                {
            "fqsen": "\\App\\Models\\Proposition\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "fillable\nLes\u0020attributs\u0020de\u0020Proposition\u0020renseignables",
            "url": "classes/App-Models-Proposition.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\Question",
            "name": "Question",
            "summary": "",
            "url": "classes/App-Models-Question.html"
        },                {
            "fqsen": "\\App\\Models\\Question\u003A\u003Asurvey\u0028\u0029",
            "name": "survey",
            "summary": "survey\nR\u00E9cup\u00E8re\u0020l\u0027objet\u0020sondage\u0020li\u00E9\u0020\u00E0\u0020une\u0020question",
            "url": "classes/App-Models-Question.html#method_survey"
        },                {
            "fqsen": "\\App\\Models\\Question\u003A\u003Apropositions\u0028\u0029",
            "name": "propositions",
            "summary": "propositions\nr\u00E9cup\u00E8re\u0020les\u0020propositions\u0020li\u00E9es\u0020\u00E0\u0020une\u0020question",
            "url": "classes/App-Models-Question.html#method_propositions"
        },                {
            "fqsen": "\\App\\Models\\Question\u003A\u003Aanswers\u0028\u0029",
            "name": "answers",
            "summary": "answers\nr\u00E9cup\u00E8re\u0020toutes\u0020les\u0020r\u00E9ponses\u0020li\u00E9es\u0020\u00E0\u0020cette\u0020question\u0020peu\u0020importe\u0020le\u0020participant",
            "url": "classes/App-Models-Question.html#method_answers"
        },                {
            "fqsen": "\\App\\Models\\Question\u003A\u003Aanswer\u0028\u0029",
            "name": "answer",
            "summary": "answer\nr\u00E9cup\u00E8re\u0020la\u0020r\u00E9ponse\u0020li\u00E9e\u0020\u00E0\u0020un\u0020participant\u0020donn\u00E9\u0020et\u0020\u00E0\u0020cette\u0020question",
            "url": "classes/App-Models-Question.html#method_answer"
        },                {
            "fqsen": "\\App\\Models\\Question\u003A\u003AfindbyQuestionBody\u0028\u0029",
            "name": "findbyQuestionBody",
            "summary": "Retourne\u0020les\u0020donn\u00E9es\u0020de\u0020question\u0020a\u0020partir\u0020du\u0020nom\u0020de\u0020la\u0020question",
            "url": "classes/App-Models-Question.html#method_findbyQuestionBody"
        },                {
            "fqsen": "\\App\\Models\\Question\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "fillable\nLes\u0020attributs\u0020de\u0020Question\u0020renseignables",
            "url": "classes/App-Models-Question.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\Survey",
            "name": "Survey",
            "summary": "",
            "url": "classes/App-Models-Survey.html"
        },                {
            "fqsen": "\\App\\Models\\Survey\u003A\u003Aquestions\u0028\u0029",
            "name": "questions",
            "summary": "questions\nR\u00E9cup\u00E8re\u0020les\u0020les\u0020questions\u0020li\u00E9es\u0020\u00E0\u0020un\u0020sondage",
            "url": "classes/App-Models-Survey.html#method_questions"
        },                {
            "fqsen": "\\App\\Models\\Survey\u003A\u003Aparticipants\u0028\u0029",
            "name": "participants",
            "summary": "participants\nr\u00E9cup\u00E8re\u0020les\u0020particiapnts\u0020de\u0020ce\u0020sondage",
            "url": "classes/App-Models-Survey.html#method_participants"
        },                {
            "fqsen": "\\App\\Models\\Survey\u003A\u003AfindByTitle\u0028\u0029",
            "name": "findByTitle",
            "summary": "Retourne\u0020le\u0020sondage\u0020par\u0020rapport\u0020\u00E0\u0020son\u0020titre",
            "url": "classes/App-Models-Survey.html#method_findByTitle"
        },                {
            "fqsen": "\\App\\Models\\Survey\u003A\u003AfindByToken\u0028\u0029",
            "name": "findByToken",
            "summary": "",
            "url": "classes/App-Models-Survey.html#method_findByToken"
        },                {
            "fqsen": "\\App\\Models\\Survey\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "fillable\nLes\u0020attributs\u0020de\u0020Sondage\u0020renseignables",
            "url": "classes/App-Models-Survey.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\User",
            "name": "User",
            "summary": "",
            "url": "classes/App-Models-User.html"
        },                {
            "fqsen": "\\App\\Models\\User\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "The\u0020attributes\u0020that\u0020are\u0020mass\u0020assignable.",
            "url": "classes/App-Models-User.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\User\u003A\u003A\u0024hidden",
            "name": "hidden",
            "summary": "The\u0020attributes\u0020that\u0020should\u0020be\u0020hidden\u0020for\u0020serialization.",
            "url": "classes/App-Models-User.html#property_hidden"
        },                {
            "fqsen": "\\App\\Models\\User\u003A\u003A\u0024casts",
            "name": "casts",
            "summary": "The\u0020attributes\u0020that\u0020should\u0020be\u0020cast.",
            "url": "classes/App-Models-User.html#property_casts"
        },                {
            "fqsen": "\\CreateUsersTable",
            "name": "CreateUsersTable",
            "summary": "",
            "url": "classes/CreateUsersTable.html"
        },                {
            "fqsen": "\\CreateUsersTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateUsersTable.html#method_up"
        },                {
            "fqsen": "\\CreateUsersTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateUsersTable.html#method_down"
        },                {
            "fqsen": "\\CreatePasswordResetsTable",
            "name": "CreatePasswordResetsTable",
            "summary": "",
            "url": "classes/CreatePasswordResetsTable.html"
        },                {
            "fqsen": "\\CreatePasswordResetsTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreatePasswordResetsTable.html#method_up"
        },                {
            "fqsen": "\\CreatePasswordResetsTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreatePasswordResetsTable.html#method_down"
        },                {
            "fqsen": "\\CreateFailedJobsTable",
            "name": "CreateFailedJobsTable",
            "summary": "",
            "url": "classes/CreateFailedJobsTable.html"
        },                {
            "fqsen": "\\CreateFailedJobsTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateFailedJobsTable.html#method_up"
        },                {
            "fqsen": "\\CreateFailedJobsTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateFailedJobsTable.html#method_down"
        },                {
            "fqsen": "\\CreatePersonalAccessTokensTable",
            "name": "CreatePersonalAccessTokensTable",
            "summary": "",
            "url": "classes/CreatePersonalAccessTokensTable.html"
        },                {
            "fqsen": "\\CreatePersonalAccessTokensTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreatePersonalAccessTokensTable.html#method_up"
        },                {
            "fqsen": "\\CreatePersonalAccessTokensTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreatePersonalAccessTokensTable.html#method_down"
        },                {
            "fqsen": "\\CreateSurveyTable",
            "name": "CreateSurveyTable",
            "summary": "",
            "url": "classes/CreateSurveyTable.html"
        },                {
            "fqsen": "\\CreateSurveyTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateSurveyTable.html#method_up"
        },                {
            "fqsen": "\\CreateSurveyTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateSurveyTable.html#method_down"
        },                {
            "fqsen": "\\CreateQuestionTable",
            "name": "CreateQuestionTable",
            "summary": "",
            "url": "classes/CreateQuestionTable.html"
        },                {
            "fqsen": "\\CreateQuestionTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateQuestionTable.html#method_up"
        },                {
            "fqsen": "\\CreateQuestionTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateQuestionTable.html#method_down"
        },                {
            "fqsen": "\\CreatePropositionsTable",
            "name": "CreatePropositionsTable",
            "summary": "",
            "url": "classes/CreatePropositionsTable.html"
        },                {
            "fqsen": "\\CreatePropositionsTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreatePropositionsTable.html#method_up"
        },                {
            "fqsen": "\\CreatePropositionsTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreatePropositionsTable.html#method_down"
        },                {
            "fqsen": "\\CreateParticipantTable",
            "name": "CreateParticipantTable",
            "summary": "",
            "url": "classes/CreateParticipantTable.html"
        },                {
            "fqsen": "\\CreateParticipantTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateParticipantTable.html#method_up"
        },                {
            "fqsen": "\\CreateParticipantTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateParticipantTable.html#method_down"
        },                {
            "fqsen": "\\CreateAnswersTable",
            "name": "CreateAnswersTable",
            "summary": "",
            "url": "classes/CreateAnswersTable.html"
        },                {
            "fqsen": "\\CreateAnswersTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateAnswersTable.html#method_up"
        },                {
            "fqsen": "\\CreateAnswersTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateAnswersTable.html#method_down"
        },                {
            "fqsen": "\\AddRelationsQuestionTable",
            "name": "AddRelationsQuestionTable",
            "summary": "",
            "url": "classes/AddRelationsQuestionTable.html"
        },                {
            "fqsen": "\\AddRelationsQuestionTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/AddRelationsQuestionTable.html#method_up"
        },                {
            "fqsen": "\\AddRelationsQuestionTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/AddRelationsQuestionTable.html#method_down"
        },                {
            "fqsen": "\\AddRelationsParticipantTable",
            "name": "AddRelationsParticipantTable",
            "summary": "",
            "url": "classes/AddRelationsParticipantTable.html"
        },                {
            "fqsen": "\\AddRelationsParticipantTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/AddRelationsParticipantTable.html#method_up"
        },                {
            "fqsen": "\\AddRelationsParticipantTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/AddRelationsParticipantTable.html#method_down"
        },                {
            "fqsen": "\\AddRelationsQuestionsTable",
            "name": "AddRelationsQuestionsTable",
            "summary": "",
            "url": "classes/AddRelationsQuestionsTable.html"
        },                {
            "fqsen": "\\AddRelationsQuestionsTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/AddRelationsQuestionsTable.html#method_up"
        },                {
            "fqsen": "\\AddRelationsQuestionsTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/AddRelationsQuestionsTable.html#method_down"
        },                {
            "fqsen": "\\AddRelationsPropositionsTable",
            "name": "AddRelationsPropositionsTable",
            "summary": "",
            "url": "classes/AddRelationsPropositionsTable.html"
        },                {
            "fqsen": "\\AddRelationsPropositionsTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/AddRelationsPropositionsTable.html#method_up"
        },                {
            "fqsen": "\\AddRelationsPropositionsTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/AddRelationsPropositionsTable.html#method_down"
        },                {
            "fqsen": "\\AddRelationsAnswersTable",
            "name": "AddRelationsAnswersTable",
            "summary": "",
            "url": "classes/AddRelationsAnswersTable.html"
        },                {
            "fqsen": "\\AddRelationsAnswersTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/AddRelationsAnswersTable.html#method_up"
        },                {
            "fqsen": "\\AddRelationsAnswersTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/AddRelationsAnswersTable.html#method_down"
        },                {
            "fqsen": "\\Database\\Seeders\\AnswersBigScreenSeeder",
            "name": "AnswersBigScreenSeeder",
            "summary": "",
            "url": "classes/Database-Seeders-AnswersBigScreenSeeder.html"
        },                {
            "fqsen": "\\Database\\Seeders\\AnswersBigScreenSeeder\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Database-Seeders-AnswersBigScreenSeeder.html#method___construct"
        },                {
            "fqsen": "\\Database\\Seeders\\AnswersBigScreenSeeder\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Run\u0020the\u0020database\u0020seeds.",
            "url": "classes/Database-Seeders-AnswersBigScreenSeeder.html#method_run"
        },                {
            "fqsen": "\\Database\\Seeders\\AnswersBigScreenSeeder\u003A\u003Agenerate_participant\u0028\u0029",
            "name": "generate_participant",
            "summary": "Generation\u0020d\u0027un\u0020participant\u0020avec\u0020ses\u0020reponses",
            "url": "classes/Database-Seeders-AnswersBigScreenSeeder.html#method_generate_participant"
        },                {
            "fqsen": "\\Database\\Seeders\\AnswersBigScreenSeeder\u003A\u003Agenerate_answers\u0028\u0029",
            "name": "generate_answers",
            "summary": "G\u00E9n\u00E9re\u0020un\u0020tableau\u0020d\u0027objet\u0020contenant\u0020l\u0027id\u0020de\u0020la\u0020question\u0020et\u0020sa\u0020reponse",
            "url": "classes/Database-Seeders-AnswersBigScreenSeeder.html#method_generate_answers"
        },                {
            "fqsen": "\\Database\\Seeders\\AnswersBigScreenSeeder\u003A\u003AbigScreenQuestion\u0028\u0029",
            "name": "bigScreenQuestion",
            "summary": "g\u00E9n\u00E9ration\u0020d\u0027un\u0020tableau\u0020contenant\u0020les\u0020question\u0020de\u0020bigscreen",
            "url": "classes/Database-Seeders-AnswersBigScreenSeeder.html#method_bigScreenQuestion"
        },                {
            "fqsen": "\\Database\\Seeders\\AnswersBigScreenSeeder\u003A\u003Agenerate_answer_by_type\u0028\u0029",
            "name": "generate_answer_by_type",
            "summary": "G\u00E9n\u00E9rateur\u0020de\u0020reponse\u0020aleatoire\u0020en\u0020fonction\u0020du\u0020type\u0020de\u0020question\nsi\u0020type\u0020A\u0020selectionne\u0020un\u0020element\u0020aleatoire\u0020dans\u0020les\u0020propositions\nsi\u0020type\u0020B\u0020une\u0020phrase\u0020avec\u00205\u0020mots\u0020aleatoir",
            "url": "classes/Database-Seeders-AnswersBigScreenSeeder.html#method_generate_answer_by_type"
        },                {
            "fqsen": "\\Database\\Seeders\\AnswersBigScreenSeeder\u003A\u003A\u0024faker",
            "name": "faker",
            "summary": "",
            "url": "classes/Database-Seeders-AnswersBigScreenSeeder.html#property_faker"
        },                {
            "fqsen": "\\Database\\Seeders\\DatabaseSeeder",
            "name": "DatabaseSeeder",
            "summary": "",
            "url": "classes/Database-Seeders-DatabaseSeeder.html"
        },                {
            "fqsen": "\\Database\\Seeders\\DatabaseSeeder\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Seed\u0020the\u0020application\u0027s\u0020database.",
            "url": "classes/Database-Seeders-DatabaseSeeder.html#method_run"
        },                {
            "fqsen": "\\Database\\Seeders\\QuestionSeeder",
            "name": "QuestionSeeder",
            "summary": "",
            "url": "classes/Database-Seeders-QuestionSeeder.html"
        },                {
            "fqsen": "\\Database\\Seeders\\QuestionSeeder\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Run\u0020the\u0020database\u0020seeds.",
            "url": "classes/Database-Seeders-QuestionSeeder.html#method_run"
        },                {
            "fqsen": "\\Database\\Seeders\\SurveySeeder",
            "name": "SurveySeeder",
            "summary": "",
            "url": "classes/Database-Seeders-SurveySeeder.html"
        },                {
            "fqsen": "\\Database\\Seeders\\SurveySeeder\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Run\u0020the\u0020database\u0020seeds.",
            "url": "classes/Database-Seeders-SurveySeeder.html#method_run"
        },                {
            "fqsen": "\\Database\\Seeders\\UserSeeder",
            "name": "UserSeeder",
            "summary": "",
            "url": "classes/Database-Seeders-UserSeeder.html"
        },                {
            "fqsen": "\\Database\\Seeders\\UserSeeder\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Run\u0020the\u0020database\u0020seeds.",
            "url": "classes/Database-Seeders-UserSeeder.html#method_run"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers",
            "name": "Controllers",
            "summary": "",
            "url": "namespaces/app-http-controllers.html"
        },                {
            "fqsen": "\\App\\Http",
            "name": "Http",
            "summary": "",
            "url": "namespaces/app-http.html"
        },                {
            "fqsen": "\\App",
            "name": "App",
            "summary": "",
            "url": "namespaces/app.html"
        },                {
            "fqsen": "\\App\\Http\\Requests",
            "name": "Requests",
            "summary": "",
            "url": "namespaces/app-http-requests.html"
        },                {
            "fqsen": "\\App\\Http\\Resources",
            "name": "Resources",
            "summary": "",
            "url": "namespaces/app-http-resources.html"
        },                {
            "fqsen": "\\App\\Models",
            "name": "Models",
            "summary": "",
            "url": "namespaces/app-models.html"
        },                {
            "fqsen": "\\Database\\Seeders",
            "name": "Seeders",
            "summary": "",
            "url": "namespaces/database-seeders.html"
        },                {
            "fqsen": "\\Database",
            "name": "Database",
            "summary": "",
            "url": "namespaces/database.html"
        }            ]
);
