on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Get commit author
        run: echo "AUTHOR=$(git log -1 --pretty=format:'%an')" >> $GITHUB_ENV
