on:
  push:
    branches:
      - main
  pull_request:
    branches:
     - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Get commit author
        run: echo "AUTHOR=$(git log -1 --pretty=format:'%an')" >> $GITHUB_ENV

      - name: Notification Discord
        env: 
          DISCORD_WEBHOOK: ${{secrets.DISCORD_WEBHOOK}}
          AUTHOR: ${{ env.AUTHOR }}
        run: |
        curl -H "Content-Type: application/json" -X POST -d '{"content": "Push effectué par : '"$AUTHOR"'"}' $DISCORD_WEBHOOK  
